# Generated by Django 3.2.8 on 2022-04-01 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='answerprepared',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='answercustom',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'text')},
        ),
    ]
